<?php

// File generated from our OpenAPI spec

namespace rtbStripe\Util;

class ObjectTypes
{
    /**
     * @var array Mapping from object types to resource classes
     */
    const mapping = [
        \rtbStripe\Account::OBJECT_NAME => \rtbStripe\Account::class,
        \rtbStripe\AccountLink::OBJECT_NAME => \rtbStripe\AccountLink::class,
        \rtbStripe\AlipayAccount::OBJECT_NAME => \rtbStripe\AlipayAccount::class,
        \rtbStripe\ApplePayDomain::OBJECT_NAME => \rtbStripe\ApplePayDomain::class,
        \rtbStripe\ApplicationFee::OBJECT_NAME => \rtbStripe\ApplicationFee::class,
        \rtbStripe\ApplicationFeeRefund::OBJECT_NAME => \rtbStripe\ApplicationFeeRefund::class,
        \rtbStripe\Balance::OBJECT_NAME => \rtbStripe\Balance::class,
        \rtbStripe\BalanceTransaction::OBJECT_NAME => \rtbStripe\BalanceTransaction::class,
        \rtbStripe\BankAccount::OBJECT_NAME => \rtbStripe\BankAccount::class,
        \rtbStripe\BillingPortal\Configuration::OBJECT_NAME => \rtbStripe\BillingPortal\Configuration::class,
        \rtbStripe\BillingPortal\Session::OBJECT_NAME => \rtbStripe\BillingPortal\Session::class,
        \rtbStripe\BitcoinReceiver::OBJECT_NAME => \rtbStripe\BitcoinReceiver::class,
        \rtbStripe\BitcoinTransaction::OBJECT_NAME => \rtbStripe\BitcoinTransaction::class,
        \rtbStripe\Capability::OBJECT_NAME => \rtbStripe\Capability::class,
        \rtbStripe\Card::OBJECT_NAME => \rtbStripe\Card::class,
        \rtbStripe\Charge::OBJECT_NAME => \rtbStripe\Charge::class,
        \rtbStripe\Checkout\Session::OBJECT_NAME => \rtbStripe\Checkout\Session::class,
        \rtbStripe\Collection::OBJECT_NAME => \rtbStripe\Collection::class,
        \rtbStripe\CountrySpec::OBJECT_NAME => \rtbStripe\CountrySpec::class,
        \rtbStripe\Coupon::OBJECT_NAME => \rtbStripe\Coupon::class,
        \rtbStripe\CreditNote::OBJECT_NAME => \rtbStripe\CreditNote::class,
        \rtbStripe\CreditNoteLineItem::OBJECT_NAME => \rtbStripe\CreditNoteLineItem::class,
        \rtbStripe\Customer::OBJECT_NAME => \rtbStripe\Customer::class,
        \rtbStripe\CustomerBalanceTransaction::OBJECT_NAME => \rtbStripe\CustomerBalanceTransaction::class,
        \rtbStripe\Discount::OBJECT_NAME => \rtbStripe\Discount::class,
        \rtbStripe\Dispute::OBJECT_NAME => \rtbStripe\Dispute::class,
        \rtbStripe\EphemeralKey::OBJECT_NAME => \rtbStripe\EphemeralKey::class,
        \rtbStripe\Event::OBJECT_NAME => \rtbStripe\Event::class,
        \rtbStripe\ExchangeRate::OBJECT_NAME => \rtbStripe\ExchangeRate::class,
        \rtbStripe\File::OBJECT_NAME => \rtbStripe\File::class,
        \rtbStripe\File::OBJECT_NAME_ALT => \rtbStripe\File::class,
        \rtbStripe\FileLink::OBJECT_NAME => \rtbStripe\FileLink::class,
        \rtbStripe\Invoice::OBJECT_NAME => \rtbStripe\Invoice::class,
        \rtbStripe\InvoiceItem::OBJECT_NAME => \rtbStripe\InvoiceItem::class,
        \rtbStripe\InvoiceLineItem::OBJECT_NAME => \rtbStripe\InvoiceLineItem::class,
        \rtbStripe\Issuing\Authorization::OBJECT_NAME => \rtbStripe\Issuing\Authorization::class,
        \rtbStripe\Issuing\Card::OBJECT_NAME => \rtbStripe\Issuing\Card::class,
        \rtbStripe\Issuing\CardDetails::OBJECT_NAME => \rtbStripe\Issuing\CardDetails::class,
        \rtbStripe\Issuing\Cardholder::OBJECT_NAME => \rtbStripe\Issuing\Cardholder::class,
        \rtbStripe\Issuing\Dispute::OBJECT_NAME => \rtbStripe\Issuing\Dispute::class,
        \rtbStripe\Issuing\Transaction::OBJECT_NAME => \rtbStripe\Issuing\Transaction::class,
        \rtbStripe\LineItem::OBJECT_NAME => \rtbStripe\LineItem::class,
        \rtbStripe\LoginLink::OBJECT_NAME => \rtbStripe\LoginLink::class,
        \rtbStripe\Mandate::OBJECT_NAME => \rtbStripe\Mandate::class,
        \rtbStripe\Order::OBJECT_NAME => \rtbStripe\Order::class,
        \rtbStripe\OrderItem::OBJECT_NAME => \rtbStripe\OrderItem::class,
        \rtbStripe\OrderReturn::OBJECT_NAME => \rtbStripe\OrderReturn::class,
        \rtbStripe\PaymentIntent::OBJECT_NAME => \rtbStripe\PaymentIntent::class,
        \rtbStripe\PaymentMethod::OBJECT_NAME => \rtbStripe\PaymentMethod::class,
        \rtbStripe\Payout::OBJECT_NAME => \rtbStripe\Payout::class,
        \rtbStripe\Person::OBJECT_NAME => \rtbStripe\Person::class,
        \rtbStripe\Plan::OBJECT_NAME => \rtbStripe\Plan::class,
        \rtbStripe\Price::OBJECT_NAME => \rtbStripe\Price::class,
        \rtbStripe\Product::OBJECT_NAME => \rtbStripe\Product::class,
        \rtbStripe\PromotionCode::OBJECT_NAME => \rtbStripe\PromotionCode::class,
        \rtbStripe\Radar\EarlyFraudWarning::OBJECT_NAME => \rtbStripe\Radar\EarlyFraudWarning::class,
        \rtbStripe\Radar\ValueList::OBJECT_NAME => \rtbStripe\Radar\ValueList::class,
        \rtbStripe\Radar\ValueListItem::OBJECT_NAME => \rtbStripe\Radar\ValueListItem::class,
        \rtbStripe\Recipient::OBJECT_NAME => \rtbStripe\Recipient::class,
        \rtbStripe\RecipientTransfer::OBJECT_NAME => \rtbStripe\RecipientTransfer::class,
        \rtbStripe\Refund::OBJECT_NAME => \rtbStripe\Refund::class,
        \rtbStripe\Reporting\ReportRun::OBJECT_NAME => \rtbStripe\Reporting\ReportRun::class,
        \rtbStripe\Reporting\ReportType::OBJECT_NAME => \rtbStripe\Reporting\ReportType::class,
        \rtbStripe\Review::OBJECT_NAME => \rtbStripe\Review::class,
        \rtbStripe\SetupAttempt::OBJECT_NAME => \rtbStripe\SetupAttempt::class,
        \rtbStripe\SetupIntent::OBJECT_NAME => \rtbStripe\SetupIntent::class,
        \rtbStripe\Sigma\ScheduledQueryRun::OBJECT_NAME => \rtbStripe\Sigma\ScheduledQueryRun::class,
        \rtbStripe\SKU::OBJECT_NAME => \rtbStripe\SKU::class,
        \rtbStripe\Source::OBJECT_NAME => \rtbStripe\Source::class,
        \rtbStripe\SourceTransaction::OBJECT_NAME => \rtbStripe\SourceTransaction::class,
        \rtbStripe\Subscription::OBJECT_NAME => \rtbStripe\Subscription::class,
        \rtbStripe\SubscriptionItem::OBJECT_NAME => \rtbStripe\SubscriptionItem::class,
        \rtbStripe\SubscriptionSchedule::OBJECT_NAME => \rtbStripe\SubscriptionSchedule::class,
        \rtbStripe\TaxId::OBJECT_NAME => \rtbStripe\TaxId::class,
        \rtbStripe\TaxRate::OBJECT_NAME => \rtbStripe\TaxRate::class,
        \rtbStripe\Terminal\ConnectionToken::OBJECT_NAME => \rtbStripe\Terminal\ConnectionToken::class,
        \rtbStripe\Terminal\Location::OBJECT_NAME => \rtbStripe\Terminal\Location::class,
        \rtbStripe\Terminal\Reader::OBJECT_NAME => \rtbStripe\Terminal\Reader::class,
        \rtbStripe\ThreeDSecure::OBJECT_NAME => \rtbStripe\ThreeDSecure::class,
        \rtbStripe\Token::OBJECT_NAME => \rtbStripe\Token::class,
        \rtbStripe\Topup::OBJECT_NAME => \rtbStripe\Topup::class,
        \rtbStripe\Transfer::OBJECT_NAME => \rtbStripe\Transfer::class,
        \rtbStripe\TransferReversal::OBJECT_NAME => \rtbStripe\TransferReversal::class,
        \rtbStripe\UsageRecord::OBJECT_NAME => \rtbStripe\UsageRecord::class,
        \rtbStripe\UsageRecordSummary::OBJECT_NAME => \rtbStripe\UsageRecordSummary::class,
        \rtbStripe\WebhookEndpoint::OBJECT_NAME => \rtbStripe\WebhookEndpoint::class,
    ];
}
